# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CRMswap_pb2 as CRMswap__pb2


class CRMswapStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GET_List = channel.unary_unary(
                '/CRMswap.CRMswap/GET_List',
                request_serializer=CRMswap__pb2.RequestGET.SerializeToString,
                response_deserializer=CRMswap__pb2.ResponseGET.FromString,
                )
        self.POST_List = channel.unary_unary(
                '/CRMswap.CRMswap/POST_List',
                request_serializer=CRMswap__pb2.RequestPOST.SerializeToString,
                response_deserializer=CRMswap__pb2.ResponsePOST.FromString,
                )


class CRMswapServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GET_List(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def POST_List(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CRMswapServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GET_List': grpc.unary_unary_rpc_method_handler(
                    servicer.GET_List,
                    request_deserializer=CRMswap__pb2.RequestGET.FromString,
                    response_serializer=CRMswap__pb2.ResponseGET.SerializeToString,
            ),
            'POST_List': grpc.unary_unary_rpc_method_handler(
                    servicer.POST_List,
                    request_deserializer=CRMswap__pb2.RequestPOST.FromString,
                    response_serializer=CRMswap__pb2.ResponsePOST.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CRMswap.CRMswap', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CRMswap(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GET_List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CRMswap.CRMswap/GET_List',
            CRMswap__pb2.RequestGET.SerializeToString,
            CRMswap__pb2.ResponseGET.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def POST_List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CRMswap.CRMswap/POST_List',
            CRMswap__pb2.RequestPOST.SerializeToString,
            CRMswap__pb2.ResponsePOST.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
