# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CRMswap.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CRMswap.proto',
  package='CRMswap',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rCRMswap.proto\x12\x07\x43RMswap\"!\n\nRequestGET\x12\x13\n\x0b\x43ustomer_id\x18\x01 \x01(\t\"h\n\x0bResponseGET\x12\x13\n\x0b\x43ustomer_id\x18\x01 \x01(\t\x12\x15\n\rCustomer_name\x18\x02 \x01(\t\x12\x15\n\rCustomer_type\x18\x03 \x01(\t\x12\x16\n\x0e\x43ustomer_email\x18\x04 \x01(\t\"#\n\x0cResponsePOST\x12\x13\n\x0b\x43ustomer_id\x18\x01 \x01(\t\"h\n\x0bRequestPOST\x12\x13\n\x0b\x43ustomer_id\x18\x01 \x01(\t\x12\x15\n\rCustomer_name\x18\x02 \x01(\t\x12\x15\n\rCustomer_type\x18\x03 \x01(\t\x12\x16\n\x0e\x43ustomer_email\x18\x04 \x01(\t2~\n\x07\x43RMswap\x12\x37\n\x08GET_List\x12\x13.CRMswap.RequestGET\x1a\x14.CRMswap.ResponseGET\"\x00\x12:\n\tPOST_List\x12\x14.CRMswap.RequestPOST\x1a\x15.CRMswap.ResponsePOST\"\x00\x62\x06proto3'
)




_REQUESTGET = _descriptor.Descriptor(
  name='RequestGET',
  full_name='CRMswap.RequestGET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Customer_id', full_name='CRMswap.RequestGET.Customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_RESPONSEGET = _descriptor.Descriptor(
  name='ResponseGET',
  full_name='CRMswap.ResponseGET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Customer_id', full_name='CRMswap.ResponseGET.Customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer_name', full_name='CRMswap.ResponseGET.Customer_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer_type', full_name='CRMswap.ResponseGET.Customer_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer_email', full_name='CRMswap.ResponseGET.Customer_email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=165,
)


_RESPONSEPOST = _descriptor.Descriptor(
  name='ResponsePOST',
  full_name='CRMswap.ResponsePOST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Customer_id', full_name='CRMswap.ResponsePOST.Customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=202,
)


_REQUESTPOST = _descriptor.Descriptor(
  name='RequestPOST',
  full_name='CRMswap.RequestPOST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Customer_id', full_name='CRMswap.RequestPOST.Customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer_name', full_name='CRMswap.RequestPOST.Customer_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer_type', full_name='CRMswap.RequestPOST.Customer_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Customer_email', full_name='CRMswap.RequestPOST.Customer_email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=308,
)

DESCRIPTOR.message_types_by_name['RequestGET'] = _REQUESTGET
DESCRIPTOR.message_types_by_name['ResponseGET'] = _RESPONSEGET
DESCRIPTOR.message_types_by_name['ResponsePOST'] = _RESPONSEPOST
DESCRIPTOR.message_types_by_name['RequestPOST'] = _REQUESTPOST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestGET = _reflection.GeneratedProtocolMessageType('RequestGET', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTGET,
  '__module__' : 'CRMswap_pb2'
  # @@protoc_insertion_point(class_scope:CRMswap.RequestGET)
  })
_sym_db.RegisterMessage(RequestGET)

ResponseGET = _reflection.GeneratedProtocolMessageType('ResponseGET', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEGET,
  '__module__' : 'CRMswap_pb2'
  # @@protoc_insertion_point(class_scope:CRMswap.ResponseGET)
  })
_sym_db.RegisterMessage(ResponseGET)

ResponsePOST = _reflection.GeneratedProtocolMessageType('ResponsePOST', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEPOST,
  '__module__' : 'CRMswap_pb2'
  # @@protoc_insertion_point(class_scope:CRMswap.ResponsePOST)
  })
_sym_db.RegisterMessage(ResponsePOST)

RequestPOST = _reflection.GeneratedProtocolMessageType('RequestPOST', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPOST,
  '__module__' : 'CRMswap_pb2'
  # @@protoc_insertion_point(class_scope:CRMswap.RequestPOST)
  })
_sym_db.RegisterMessage(RequestPOST)



_CRMSWAP = _descriptor.ServiceDescriptor(
  name='CRMswap',
  full_name='CRMswap.CRMswap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=310,
  serialized_end=436,
  methods=[
  _descriptor.MethodDescriptor(
    name='GET_List',
    full_name='CRMswap.CRMswap.GET_List',
    index=0,
    containing_service=None,
    input_type=_REQUESTGET,
    output_type=_RESPONSEGET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='POST_List',
    full_name='CRMswap.CRMswap.POST_List',
    index=1,
    containing_service=None,
    input_type=_REQUESTPOST,
    output_type=_RESPONSEPOST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRMSWAP)

DESCRIPTOR.services_by_name['CRMswap'] = _CRMSWAP

# @@protoc_insertion_point(module_scope)
